# Generated by Django 2.2.4 on 2019-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='3i1415926543PI.jpg', upload_to='profile_pics'),
        ),
    ]
