# Generated by Django 2.2.4 on 2019-12-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191219_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_is_seller',
            new_name='is_seller',
        ),
    ]
