# Generated by Django 2.2.4 on 2019-12-20 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_adminwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminwallet',
            old_name='money',
            new_name='djangomoney',
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='adminuser',
            field=models.OneToOneField(default=0 , on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
