# Generated by Django 2.2.4 on 2019-12-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191220_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminWallet',
        ),
    ]
