# Generated by Django 2.2.4 on 2019-12-20 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
