# Generated by Django 2.2.4 on 2019-12-31 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191231_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='ValidationYear',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='WithdrawAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(-0.0)]),
        ),
    ]
