# Generated by Django 2.2.4 on 2020-01-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200102_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='3i1415926543PI.jpg', upload_to='images'),
        ),
    ]
