# Generated by Django 2.2.4 on 2019-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_auto_20191218_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='images'),
        ),
    ]
