# Generated by Django 2.2.4 on 2019-12-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_auto_20191220_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
