# Generated by Django 2.2.4 on 2019-12-23 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecom', '0011_product_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clicks',
        ),
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.ManyToManyField(related_name='clicks', to=settings.AUTH_USER_MODEL),
        ),
    ]
