# Generated by Django 2.2.4 on 2019-12-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0018_auto_20191224_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='time_you_will_take_to_send_the_product',
            new_name='shipping_time',
        ),
    ]
