# Generated by Django 2.2.4 on 2019-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
