# Generated by Django 2.2.4 on 2019-12-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0021_product_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
    ]
