# Generated by Django 2.2.4 on 2019-12-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0026_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.AddCart'),
        ),
    ]
