# Generated by Django 2.2.4 on 2019-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0028_review_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
