# Generated by Django 2.2.4 on 2019-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0033_order_date_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('not_shipped', 'not_shipped'), ('order_dispatched', 'order_dispatched')], default='not_shipped', max_length=100),
        ),
    ]
