# Generated by Django 2.2.4 on 2019-12-30 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0035_auto_20191229_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=8, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
