# Generated by Django 2.2.4 on 2019-12-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0037_auto_20191231_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
