# Generated by Django 2.2.4 on 2019-12-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0038_orderstatus_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_track_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not shipped', 'Not shipped'), ('Order dispatched', 'Order dispatched')], default='Not shipped', max_length=100),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
