# Generated by Django 2.2.4 on 2019-12-31 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0039_auto_20191231_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_seller_received',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=8, validators=[django.core.validators.MinValueValidator(-0.0)]),
        ),
    ]
