# Generated by Django 2.2.4 on 2019-12-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0040_order_price_seller_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
