# Generated by Django 2.2.4 on 2020-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0041_auto_20191231_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='Not Provided Yet', max_length=200),
        ),
    ]
