# Generated by Django 2.2.4 on 2020-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0042_auto_20200102_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='Error', max_length=800),
        ),
    ]
