# Generated by Django 2.2.4 on 2020-01-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0043_review_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='number',
            new_name='rating',
        ),
    ]
