# Generated by Django 2.2.4 on 2020-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0044_auto_20200102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='What do you think about this product', max_length=20),
        ),
    ]
