# Generated by Django 2.2.4 on 2020-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0045_auto_20200102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='Error', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='What do you think about this product?', max_length=800),
        ),
    ]
