# Generated by Django 2.2.4 on 2020-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0047_auto_20200102_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Title of your Review', max_length=100),
        ),
    ]
