# Generated by Django 2.2.4 on 2020-01-02 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0048_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
