# Generated by Django 2.2.4 on 2020-01-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0049_review_date_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
    ]
